version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run build -- --prod
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/angular-crud-app'
  discard-paths: no # Ensure directory structure is preserved
